/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.1/userguide/building_java_projects.html in the Gradle documentation.
 */

repositories {
    mavenCentral()
}

plugins {
    id("java")
    id("application")
    id("com.gradleup.shadow").version("9.2.2")
    id("org.openjfx.javafxplugin").version("0.1.0")
}

dependencies {
    implementation("info.picocli:picocli:4.7.7")
    implementation("com.github.almasb:fxgl:21.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "dev.haruki7049.Spelling.Main"
}

javafx {
    version = "21.0.8"
    modules = listOf("javafx.controls", "javafx.base", "javafx.graphics", "javafx.fxml", "javafx.media")
}

tasks.named<Test>("test") {
    // Use TestNG for unit tests.
    useTestNG()
}

tasks.named<CreateStartScripts>("startScripts") {
    dependsOn(tasks.named("shadowJar"))
}
