#!/usr/bin/env bash
# Regenerate llvm.golden from llvm-cases.txt using LLVM's RISC-V assembler.
#
# Each case in llvm-cases.txt is separated by a line containing only "---".
# It is assembled with llvm-mc and linked with ld.lld at 0x200 (the base
# used by TestLLVMGolden), and the words of .text are recorded after "=>".
# Cases that LLVM rejects are recorded as "=> error".
#
# Usage (from the repository root):
#   nix shell nixpkgs#llvm nixpkgs#lld -c internal/asm/testdata/gen-llvm-golden.sh
set -euo pipefail

dir=$(cd "$(dirname "$0")" && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

emit() {
  local src=$1 words
  printf '%s\n' "$src" >"$tmp/c.s"
  if llvm-mc -triple=riscv32 -mattr=-relax,-c -filetype=obj "$tmp/c.s" -o "$tmp/c.o" 2>/dev/null &&
    ld.lld -m elf32lriscv --no-relax --image-base=0 -e 0x200 -Ttext=0x200 "$tmp/c.o" -o "$tmp/c.elf" 2>/dev/null; then
    llvm-objcopy -O binary -j .text "$tmp/c.elf" "$tmp/c.bin"
    words=$(od -An -v -tx4 --endian=little "$tmp/c.bin" | xargs)
  else
    words=error
  fi
  printf '%s\n=> %s\n' "$src" "$words"
}

{
  echo "# Generated by gen-llvm-golden.sh from llvm-cases.txt. Do not edit."
  first=1
  src=
  while IFS= read -r line || [[ -n $line ]]; do
    if [[ $line == --- ]]; then
      [[ $first == 1 ]] || echo ---
      first=0
      emit "$src"
      src=
    else
      src+=${src:+$'\n'}$line
    fi
  done <"$dir/llvm-cases.txt"
  [[ $first == 1 ]] || echo ---
  emit "$src"
} >"$dir/llvm.golden"
